# Advanced Array Manipulation

## 1. Reshaping Arrays

In [1]:
import numpy as np

In [2]:
array = np.arange(8).reshape((4, 2), order='C')   #C order = row major
array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [3]:
array.reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
array = np.arange(15).reshape((5, -1))
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [5]:
np.ones((10, 5)).shape

(10, 5)

## 2. Flattening/Raveling
* oppositee of reshape: matrix => one-dimension

In [6]:
array = np.arange(15).reshape((5, -1), order='C')
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [7]:
#ravel() does not copy
array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [9]:
#flatten() copies the data
array.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

* The array we have seen so far reshaped/raveled via C order 

## 3. C Versus Fortran Order

In [10]:
array = np.arange(12).reshape((3, 4), order='C')
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
array.ravel(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
array.ravel(order='F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

## 4. Concatenating and Splitting Arrays

In [13]:
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2 = np.array([[7, 8, 9], [10, 11, 12]])

In [14]:
np.concatenate([array_1, array_2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.concatenate([array_1, array_2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 4.1 Alternative to np.concatenate()

In [16]:
np.vstack((array_1, array_2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.hstack((array_1, array_2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### 4.2 Splitting arrays

In [18]:
array = np.random.randn(5, 2)
array

array([[ 0.48743595,  0.58832557],
       [-0.57080513,  0.05771434],
       [-1.13584815,  1.56986624],
       [ 0.53505945,  0.95173418],
       [ 0.19469929, -1.46722984]])

In [19]:
first, second, third = np.split(array, [1, 2])

In [20]:
first

array([[0.48743595, 0.58832557]])

In [21]:
second

array([[-0.57080513,  0.05771434]])

In [22]:
third

array([[-1.13584815,  1.56986624],
       [ 0.53505945,  0.95173418],
       [ 0.19469929, -1.46722984]])

## 5. Repeating Elements: tile and repeat

### 5.1 repeat()
* repeat(n) replicates each item in the array n times

In [23]:
array = np.arange(3)
array

array([0, 1, 2])

In [24]:
array.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [25]:
#each item's repeatition depends on by the integer value in the input list
array.repeat([1, 2, 3])

array([0, 1, 1, 2, 2, 2])

In [26]:
array = np.random.randn(2, 2)
array.repeat(2, axis=0)

array([[-0.3121583 , -0.82675972],
       [-0.3121583 , -0.82675972],
       [ 0.27720673,  1.96136396],
       [ 0.27720673,  1.96136396]])

In [27]:
array.repeat([1, 2], axis=0)

array([[-0.3121583 , -0.82675972],
       [ 0.27720673,  1.96136396],
       [ 0.27720673,  1.96136396]])

### 5.2 tile()
* stacking the entire copy of an array

In [28]:
array

array([[-0.3121583 , -0.82675972],
       [ 0.27720673,  1.96136396]])

In [29]:
# 3 is the number of copies
np.tile(array, 3)

array([[-0.3121583 , -0.82675972, -0.3121583 , -0.82675972, -0.3121583 ,
        -0.82675972],
       [ 0.27720673,  1.96136396,  0.27720673,  1.96136396,  0.27720673,
         1.96136396]])

In [30]:
#creates an array of 2x2 from array variable
np.tile(array, (2, 2))

array([[-0.3121583 , -0.82675972, -0.3121583 , -0.82675972],
       [ 0.27720673,  1.96136396,  0.27720673,  1.96136396],
       [-0.3121583 , -0.82675972, -0.3121583 , -0.82675972],
       [ 0.27720673,  1.96136396,  0.27720673,  1.96136396]])

## 6. Fancy Indexing Equivalents: take and put

In [31]:
array = np.arange(10) * 100
indexes = [7, 1, 2, 6]
array[indexes]

array([700, 100, 200, 600])

### 6.1 take() 
* An alternative approach

In [32]:
array.take(indexes)

array([700, 100, 200, 600])

### 6.2 put()
* put() inserts desired values to indexed items

In [33]:
array.put(indexes, 50)

In [34]:
array

array([  0,  50,  50, 300, 400, 500,  50,  50, 800, 900])