# NumPy ndarray: A Multidimensional Array Object

In [1]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[ 0.13921056,  0.90949854,  2.32102524],
       [ 0.22573346, -0.69334384, -1.34950095]])

In [3]:
data * 10

array([[  1.3921056 ,   9.09498539,  23.21025245],
       [  2.25733458,  -6.93343837, -13.49500951]])

In [4]:
data + data

array([[ 0.27842112,  1.81899708,  4.64205049],
       [ 0.45146692, -1.38668767, -2.6990019 ]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

## 1. Creating ndarrays

In [7]:
data_1 = [6, 7.5, 8, 0, 1]
#converts list to np.array
array_1 = np.array(data_1)
array_1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data_2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
#nested lists to multidimensionla array
array_2 = np.array(data_2)
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
array_2.shape

(2, 4)

In [10]:
array_2.dtype

dtype('int32')

In [11]:
array_2.ndim

2

### 1.1 Zeros, ones and empty

In [12]:
#tuple of dimensions
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.empty((3, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 2. Data Types for ndarrays

In [16]:
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.float64)
array_2 = np.array([1, 2, 3, 4, 5], dtype=np.int32)

In [17]:
array_1.dtype

dtype('float64')

In [18]:
array_2.dtype

dtype('int32')

### 2.1 Casting dtypes with astype()

In [19]:
array = np.array([1, 2, 3])
array.dtype

dtype('int32')

In [20]:
float_array = array.astype(np.float64)
float_array.dtype

dtype('float64')

In [21]:
array = np.array([2.2, 3.7, 4.1])
array.astype(np.int32)

array([2, 3, 4])

In [22]:
numeric_strings = np.array(['4.5', '4', '3'], dtype=np.string_)
numeric_strings.astype(np.float64)

array([4.5, 4. , 3. ])

Calling astype() creates always a copy of the array object

## 3. Arithmetic with NumPy Arrays

In [23]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#elements of array multiplied
array * array

array([[ 1,  4,  9],
       [16, 25, 36]])

In [25]:
array - array

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
1 / array

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [27]:
array ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
array_2 = np.array([[1, 2, 8], [3, 5, 2]])
#comparison return boolean values
array == array_2

array([[ True,  True, False],
       [False,  True, False]])

## 4. Basic Indexing and Slicing

In [29]:
array = np.arange(10)
array[4]

4

In [30]:
array[5:8]

array([5, 6, 7])

In [31]:
#scalar value is broadcasted to assigned slice
#arrays are not copied, directly to source
array[5:8] = 12
array

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
array_slice = array[5:8]
array_slice

array([12, 12, 12])

In [33]:
#changes on binding variables directly eefects to the source object either
array_slice[1] = 6289
array

array([   0,    1,    2,    3,    4,   12, 6289,   12,    8,    9])

In [34]:
#copy if you dont want changes on the source object
array_slice_2 = array.copy()
array_slice_2[:2] = 14
array
#no changes in the source

array([   0,    1,    2,    3,    4,   12, 6289,   12,    8,    9])

In [35]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#iindex returns 1d vector
array_2d[1]

array([4, 5, 6])

In [36]:
#accessing elements recursively
array_2d[2][1]

8

In [37]:
#alternatively to recursion
array_2d[0, 2]

3

### 4.1 3D array

In [38]:
array = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  [[7, 8, 9],
                  [10, 11, 12]]])

In [39]:
array[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [40]:
old_values = array[0].copy()
array[0] = 18
array

array([[[18, 18, 18],
        [18, 18, 18]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
array[0] = old_values
array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
array[1, 0, 2]

9

### 4.2 Indexing with slices

In [43]:
array = np.arange(10)
array[1:5]

array([1, 2, 3, 4])

In [44]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
array_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [46]:
array_2d[:2, 1:] = 0
#reflects to source code too
array_2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 5. Boolean Indexing

In [47]:
names = np.array(['Bob', 'Joe', 'Willie', 'Bob', 'Willie', 'Joe', 'Joe'])
data = np.random.randn(7,4)
#randomly normal distributed data

In [48]:
names

array(['Bob', 'Joe', 'Willie', 'Bob', 'Willie', 'Joe', 'Joe'], dtype='<U6')

In [49]:
data

array([[ 0.3059135 ,  1.65251137, -0.35366186,  0.60987409],
       [ 0.83852828, -1.62094005, -0.12648678,  0.64174173],
       [ 0.2992105 ,  1.81679864, -1.70004414, -0.69743302],
       [ 2.00133285,  1.5203907 , -1.43259469, -0.2342789 ],
       [-0.38617423,  0.54509486,  0.72327764, -0.70759865],
       [ 0.76161872,  0.56882696,  0.31062023, -0.4056114 ],
       [ 1.61674095, -0.63367635, -1.56278959,  0.91760079]])

In [50]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [51]:
#returns 0, 3 indexes of data array
data[names == 'Bob']

array([[ 0.3059135 ,  1.65251137, -0.35366186,  0.60987409],
       [ 2.00133285,  1.5203907 , -1.43259469, -0.2342789 ]])

In [52]:
#index defining return True values only
data[names == 'Bob', 2:]

array([[-0.35366186,  0.60987409],
       [-1.43259469, -0.2342789 ]])

In [53]:
multiple_boolean = (names == 'Bob') | (names == 'Willie')
multiple_boolean

array([ True, False,  True,  True,  True, False, False])

In [54]:
#returns 0, 2, 3, 4 index rows
data[multiple_boolean]

array([[ 0.3059135 ,  1.65251137, -0.35366186,  0.60987409],
       [ 0.2992105 ,  1.81679864, -1.70004414, -0.69743302],
       [ 2.00133285,  1.5203907 , -1.43259469, -0.2342789 ],
       [-0.38617423,  0.54509486,  0.72327764, -0.70759865]])

In [55]:
data[data < 0] = 0
data

array([[0.3059135 , 1.65251137, 0.        , 0.60987409],
       [0.83852828, 0.        , 0.        , 0.64174173],
       [0.2992105 , 1.81679864, 0.        , 0.        ],
       [2.00133285, 1.5203907 , 0.        , 0.        ],
       [0.        , 0.54509486, 0.72327764, 0.        ],
       [0.76161872, 0.56882696, 0.31062023, 0.        ],
       [1.61674095, 0.        , 0.        , 0.91760079]])

## 6. Fancy Indexing

In [56]:
#indexing the rows with anything that is fancy
array = np.empty((8, 4))

for i in range(8):
    array[i] = i
    
array

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [57]:
#selecting out a subset in particular order
array[[5, 3, 7, 2]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [58]:
#the negative as lists is for the rows as well
array[[-4, -2, -7]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.],
       [1., 1., 1., 1.]])

In [59]:
array = np.arange(32).reshape((8, 4))
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
#tuple zip form (1,2), (4,3)
array[[1, 4], [2, 3]]

array([ 6, 19])

## 7. Transposing Arrays and Swapping Axes

In [61]:
array = np.arange(15).reshape((3, 5))
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
#no copy of the source
array.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [63]:
array = np.random.randn(6, 3)
array

array([[ 0.45240003,  0.18930354, -0.22114328],
       [ 1.77763384, -0.11626495,  0.67399339],
       [-0.91540631, -0.589252  ,  0.19555278],
       [-0.66064942,  0.89154852,  1.25561416],
       [ 0.51076875, -1.49336027,  0.50636885],
       [-0.8454429 , -1.2919207 , -0.13594869]])

In [64]:
# (3,6) X (6, 3) = (3, 3)
np.dot(array.transpose(), array)

array([[5.61473263, 0.15885184, 0.46311146],
       [0.15885184, 5.09061405, 0.30342985],
       [0.46311146, 0.30342985, 2.39287071]])

In [65]:
array = np.arange(16).reshape((2, 2, 4))
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [66]:
#for higher dimension we accept tuple of axes
array.transpose((2, 0, 1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])

### 7.1 swapaxes

In [67]:
array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [68]:
#swapping axes
array.swapaxes(0, 1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])