# Universal Functions: Fast Element-Wise Array Functions

## 1. Unary functions
* ops inside an array

In [1]:
import numpy as np

In [2]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### modf()
* vectorized implementation of Python's built in divmod()

In [5]:
array = np.random.randn(7) * 5
array

array([-1.77479337,  1.5646932 ,  6.34259767,  4.32396552, -1.34567453,
        2.19046118, -2.02998129])

In [6]:
remainder, whole = np.modf(array)

In [7]:
remainder

array([-0.77479337,  0.5646932 ,  0.34259767,  0.32396552, -0.34567453,
        0.19046118, -0.02998129])

In [8]:
whole

array([-1.,  1.,  6.,  4., -1.,  2., -2.])

In [9]:
array

array([-1.77479337,  1.5646932 ,  6.34259767,  4.32396552, -1.34567453,
        2.19046118, -2.02998129])

In [10]:
#accept an optional out argument for negative values
np.sqrt(array)

<ipython-input-10-d8fa42088d52>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(array)


array([       nan, 1.25087697, 2.51845144, 2.07941471,        nan,
       1.48002067,        nan])

## 2. Binary functions
* ops between 2 or more arrays

In [11]:
x = np.random.randn(8)
y = np.random.randn(8)

In [12]:
x

array([-0.96907103, -2.20118094, -0.38837153,  0.03428807,  0.66794632,
        0.0305573 ,  0.46753436,  0.41759814])

In [13]:
y

array([ 2.45751036,  0.4386242 , -0.51705247, -1.56631352, -0.08315758,
       -0.67299747,  0.82007687,  0.84830695])

In [14]:
#estestvennit otbor from 2 array items
np.maximum(x, y)

array([ 2.45751036,  0.4386242 , -0.38837153,  0.03428807,  0.66794632,
        0.0305573 ,  0.82007687,  0.84830695])