# Linear Algebra

* `np.linalg` has all the capabilities to perform high-level linear algebra for machine learning and data science

In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

In [3]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [5]:
np.dot(x, y)

array([[ 28,  64],
       [ 67, 181]])

In [6]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [7]:
x @ np.ones(3)

array([ 6., 15.])

In [8]:
from numpy.linalg import inv, qr

In [9]:
X = np.random.randn(5, 5)
mat_mul = np.dot(X.T, X)

In [10]:
inv(mat_mul)

array([[   64.51341088,   -81.78744168,  -374.11127243,    82.33368682,
          389.45242974],
       [  -81.78744168,   104.69346105,   475.36836326,  -104.57372776,
         -495.90591613],
       [ -374.11127243,   475.36836326,  2176.08103523,  -479.12347576,
        -2264.56821147],
       [   82.33368682,  -104.57372776,  -479.12347576,   105.59331499,
          498.49507338],
       [  389.45242974,  -495.90591613, -2264.56821147,   498.49507338,
         2358.54215903]])

In [11]:
np.dot(mat_mul, inv(mat_mul))

array([[ 1.00000000e+00, -4.14285402e-14, -2.23787195e-13,
        -3.97032909e-14, -7.87976429e-14],
       [ 1.24514506e-13,  1.00000000e+00, -1.04397256e-12,
         2.15456134e-13,  3.16033974e-12],
       [-2.21373632e-14,  1.41065525e-13,  1.00000000e+00,
         4.43896170e-14,  2.79959386e-12],
       [ 7.80730309e-14, -4.41732390e-15, -1.09673137e-12,
         1.00000000e+00,  2.82525645e-13],
       [ 2.07623665e-13, -1.05314973e-13,  4.12713864e-13,
         5.18239191e-13,  1.00000000e+00]])